const appname = "FURNIHUSH";
const appversion = "Version 1.0.0";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Your Name";
const forgetpassword = "Forget Password";
const login = "Log In";
const signup = "Sign Up";
const createNewAccount = "Create New Account";
const loginwith = "Log in With";
const privacyPolicy = "Privacy Policy";
const termandCondition = "Terms and Condition";
const alreadyhaveacc = "Already have an Account? ";
// strings for home_controller
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Seacrh Anything....",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sales",
    topsellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    girlWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T-Shirts",
    featuredProduct = "Featured Products",
    girlsDress = "Girls Dress",
    womenDress = "Women Dress";

// categories strings
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing Fashion",
    compAccess = "Computer and Accessories",
    automobile = "Automobile",
    kidtoy = "Kids & Toys",
    sport = "Sports",
    jewellary = "Jewellary",
    furniture = "Furniture",
    cellphone = "Cellphone & Tab";
